dist: trusty
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

before_script:
  - npm install -g @angular/cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ng lint
  - ng test --code-coverage
  - ng e2e
  - ng build --prod --aot

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
